openapi: 3.0.0
info:
  title: Migration Info API
  version: 1.0.0
  description: |
    This document specifies the Migration Info API. It provides access to a database that keeps track of information
    about the migration from EASY to a Data Station.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: 'https://dar.dans.knaw.nl'
    description: Local test VM for Data Station Archaeology
  - url: 'https://dss.dans.knaw.nl'
    description: Local test VM for Data Station Social Sciences

paths:
  /:
    get:
      summary: Returns a description of the service.
      responses:
        200:
          description: Description of the service
          content:
            text/plain:
              schema:
                type: string
                description: A plain text, human readable description of the service
                example: |
                  Migration Info Service is running.


  /datasets/{id}/datafiles/actions/load-from-dataverse:
    parameters:
      - $ref: "#/components/parameters/DatasetIdentifier"
      - $ref: "#/components/parameters/PersistentIdentifier"
    post:
      summary: Adds the records for the unique data files in the specified dataset
      responses:
        200:
          description: OK. Added data file records
        404:
          description: Not Found. Could not find the specified dataset

  /datasets/{id}/datafiles:
    parameters:
      - $ref: "#/components/parameters/DatasetIdentifier"
      - $ref: "#/components/parameters/PersistentIdentifier"
    get:
      summary: Retrieves the unique datafiles from the specified dataset
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataFile'
        404:
          description: Not Found. Not records for specified Dataset could be found.

  /datasets/{id}/datafiles/{storageId}:
    parameters:
      - $ref: "#/components/parameters/DatasetIdentifier"
      - $ref: "#/components/parameters/StorageIdentifier"
      - $ref: "#/components/parameters/PersistentIdentifier"
    get:
      summary: Retrieves the datafile record with the specified storage identifier and dataset
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataFile'
        404:
          description: Not Found
    put:
      summary: Writes/updates the datafile record with the specified storage identifier and dataset
      responses:
        201:
          description: Created. Created new record.
        204:
          description: No Content. Updated existing record.


  /datasets/actions/load-from-dataverse:
    post:
      summary: Loads all datafile records for all datasets in the configured dataverse
      responses:
        201:
          description: Created.
        400:
          description: Bad Request. Configured dataverse could not be found.

components:

  parameters:

    DatasetIdentifier:
      description: |
        Database ID of the dataset or the string `:persistentId`to indicate that a DOI is
        specified in the query parameter `persistentId`
      in: path
      name: id
      schema:
        type: string
      required: true

    StorageIdentifier:
      description: Storage identifier of a file
      in: path
      name: storageId
      schema:
        type: string
      required: true

    PersistentIdentifier:
      description: The DOI of the dataset
      in: query
      name: persistentId
      schema:
        type: string
      required: false


  schemas:

    DataFile:
      type: object
      properties:
        storageIdentifier:
          type: string
        fileName:
          type: string
        mimeType:
          type: string
        checksum:
          $ref: "#/components/schemas/Checksum"
        fileSize:
          type: integer

    Checksum:
      type: object
      properties:
        "@type":
          type: string
        "@value":
          type: string
